---
- name: create librenms db with exposed port
  docker_container:
    name: "{{ librenms.mysql_db_host }}"
    image: "{{ librenms.mysql_container_image }}:{{ librenms.mysql_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    volumes:
      - "{{ librenms.db_volume }}:/var/lib/mysql"
      - "{{ librenms.db_config_volume }}:/etc/mysql/conf.d"
    env:
      MYSQL_ROOT_PASSWORD: "{{ librenms.mysql_root_pw }}"
      MYSQL_PASSWORD: "{{ librenms.mysql_db_pw }}"
      MYSQL_DATABASE: "{{ librenms.mysql_db_name }}"
      MYSQL_USER: "{{ librenms.mysql_db_user }}"
    ports:
      - "3306:3306"
  when:
    - librenms.distributed
    - librenms.sql

- name: create librenms db without exposed port
  docker_container:
    name: "{{ librenms.mysql_db_host }}"
    image: "{{ librenms.mysql_container_image }}:{{ librenms.mysql_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    volumes:
      - "{{ librenms.db_volume }}:/var/lib/mysql"
      - "{{ librenms.db_config_volume }}:/etc/mysql/conf.d"
    env:
      MYSQL_ROOT_PASSWORD: "{{ librenms.mysql_root_pw }}"
      MYSQL_PASSWORD: "{{ librenms.mysql_db_pw }}"
      MYSQL_DATABASE: "{{ librenms.mysql_db_name }}"
      MYSQL_USER: "{{ librenms.mysql_db_user }}"
  when: not librenms.distributed

- name: custom db config
  lineinfile:
    line: "{{ item }}"
    path: "{{ librenms.db_config_volume }}/librenms.cnf"
    create: true
  with_items: "{{ librenms.custom_db_config }}"
  notify:
    - restart db

- name: create librenms
  docker_container:
    name: librenms
    image: "{{ librenms.librenms_container_image }}:{{ librenms.librenms_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    links:
      - "{{ librenms.mysql_db_host }}"
    volumes:
      - "{{ librenms.logs_volume }}:/opt/librenms/logs"
      - "{{ librenms.rrd_volume }}:/opt/librenms/rrd"
      - "{{ librenms.conf_d }}:/opt/librenms/conf.d"
      - "{{ librenms.includes }}:/opt/librenms/includes/custom"
    ports:
      - "80:80"
    env:
      APP_KEY: "{{ librenms.app_key }}"
      DB_HOST: "{{ librenms.mysql_db_host }}"
      DB_NAME: "{{ librenms.mysql_db_name }}"
      DB_USER: "{{ librenms.mysql_db_user }}"
      DB_PASS: "{{ librenms.mysql_db_pw }}"
      BASE_URL: "{{ librenms.base_url }}"
      POLLERS: "{{ librenms.pollers }}"
      DISCOVERY_THREADS: "{{ librenms.discovery_threads }}"
  notify:
    - set up db
    - set up admin
  when: librenms.sql

- name: create librenms
  docker_container:
    name: librenms
    image: "{{ librenms.librenms_container_image }}:{{ librenms.librenms_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    volumes:
      - "{{ librenms.logs_volume }}:/opt/librenms/logs"
      - "{{ librenms.rrd_volume }}:/opt/librenms/rrd"
      - "{{ librenms.conf_d }}:/opt/librenms/conf.d"
      - "{{ librenms.includes }}:/opt/librenms/includes/custom"
    ports:
      - "80:80"
    env:
      APP_KEY: "{{ librenms.app_key }}"
      DB_HOST: "{{ librenms.mysql_db_host }}"
      DB_NAME: "{{ librenms.mysql_db_name }}"
      DB_USER: "{{ librenms.mysql_db_user }}"
      DB_PASS: "{{ librenms.mysql_db_pw }}"
      BASE_URL: "{{ librenms.base_url }}"
      POLLERS: "{{ librenms.pollers }}"
      DISCOVERY_THREADS: "{{ librenms.discovery_threads }}"
  when: not librenms.sql
