---
- name: create librenms db with exposed port
  docker_container:
    name: db
    image: "{{ librenms.mysql_container_image }}:{{ librenms.mysql_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    volumes:
      - "{{ librenms.db_volume }}:/var/lib/mysql"
      - "{{ librenms.db_config_volume }}:/etc/mysql/conf.d"
    env:
      MYSQL_ROOT_PASSWORD: "{{ librenms.mysql_root_pw }}"
      MYSQL_PASSWORD: "{{ librenms.mysql_db_pw }}"
      MYSQL_DATABASE: "{{ librenms.mysql_db_name }}"
      MYSQL_USER: "{{ librenms.mysql_db_user }}"
    ports:
      - "3306:3306"
  when:
    - librenms.sql

- name: custom db config
  lineinfile:
    line: "{{ item }}"
    path: "{{ librenms.db_config_volume }}/librenms.cnf"
    create: true
  with_items: "{{ librenms.custom_db_config }}"
  notify:
    - restart db
  when:
    - librenms.sql

- name: create rrdcached
  docker_container:
    name: rrdcached
    image: crazymax/rrdcached:1.7.0
    state: started
    restart_policy: always
    volumes:
      - "/data:/data"
    env:
      WRITE_THREADS: "{{ librenms.rrdcached_threads }}"
    ports:
      - 42217:42217
  when:
    - librenms.rrdcached

- name: create memcached
  docker_container:
    name: memcached
    image: bitnami/memcached:1.5.12
    state: started
    restart_policy: always
    ports:
      - 11211:11211/udp
      - 11211:11211
    env:
      MEMCACHED_CACHE_SIZE: "{{ librenms.memcached_size }}"
  when:
    - librenms.memcached
