---
- name: create librenms poller with nginx and custom dns
  docker_container:
    name: librenms
    image: "{{ librenms.librenms_container_image }}:{{ librenms.librenms_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    dns_servers: "{{ librenms.dns_servers }}"
    dns_search_domains: "{{ librenms.search_domains }}"
    volumes:
      - "{{ librenms.logs_volume }}:/opt/librenms/logs"
      - "{{ librenms.rrd_volume }}:/opt/librenms/rrd"
      - "{{ librenms.conf_d }}:/opt/librenms/conf.d"
      - "{{ librenms.includes }}:/opt/librenms/includes/custom"
      - "{{ librenms.weathermap }}:/opt/librenms/html/plugins/Weathermap/configs"
    ports:
      - "80:80"
      - "514:514/udp"
    env:
      ALERTS_ENABLE: "{{ librenms.alerts_enable }}"
      APP_KEY: "{{ librenms.app_key }}"
      BASE_URL: "{{ librenms.base_url }}"
      BILLING_CALCULATE_ENABLE: "{{ librenms.billing_calc_enable }}"
      DAILY_ENABLE: "{{ librenms.daily_enable }}"
      DB_HOST: "{{ librenms.mysql_db_host }}"
      DB_NAME: "{{ librenms.mysql_db_name }}"
      DB_PASS: "{{ librenms.mysql_db_pw }}"
      DB_USER: "{{ librenms.mysql_db_user }}"
      DISCOVERY_ENABLE: "{{ librenms.poller_discovery }}"
      DISCOVERY_THREADS: "{{ librenms.discovery_threads }}"
      ENABLE_SYSLOG: "{{ librenms.enable_syslog }}"
      MEMCACHED_HOST: "{{ librenms.memcached_host }}"
      NGINX_ENABLE: "{{ librenms.nginx_enable }}"
      POLLERS: "{{ librenms.pollers }}"
      POLLERS_CRON: "{{ librenms.pollers_cron }}"
      RRDCACHED_CONNECT: "{{ librenms.rrdcached_connect }}"
      RRDCACHED_ENABLE: "false"
      WEATHERMAP_ENABLE: "true"
      WEATHERMAP_CRON: "{{ librenms.weathermap_cron }}"
  when:
    - librenms.poller
    - librenms.nginx_enable
    - librenms.dns_servers != []
    - librenms.search_domains != []

- name: create librenms poller without custom dns
  docker_container:
    name: librenms
    image: "{{ librenms.librenms_container_image }}:{{ librenms.librenms_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    volumes:
      - "{{ librenms.logs_volume }}:/opt/librenms/logs"
      - "{{ librenms.rrd_volume }}:/opt/librenms/rrd"
      - "{{ librenms.conf_d }}:/opt/librenms/conf.d"
      - "{{ librenms.includes }}:/opt/librenms/includes/custom"
    ports:
      - "80:80"
      - "514:514/udp"
    env:
      ALERTS_ENABLE: "{{ librenms.alerts_enable }}"
      APP_KEY: "{{ librenms.app_key }}"
      BASE_URL: "{{ librenms.base_url }}"
      BILLING_CALCULATE_ENABLE: "{{ librenms.billing_calc_enable }}"
      DAILY_ENABLE: "{{ librenms.daily_enable }}"
      DB_HOST: "{{ librenms.mysql_db_host }}"
      DB_NAME: "{{ librenms.mysql_db_name }}"
      DB_PASS: "{{ librenms.mysql_db_pw }}"
      DB_USER: "{{ librenms.mysql_db_user }}"
      DISCOVERY_ENABLE: "{{ librenms.poller_discovery }}"
      DISCOVERY_THREADS: "{{ librenms.discovery_threads }}"
      ENABLE_SYSLOG: "{{ librenms.enable_syslog }}"
      MEMCACHED_HOST: "{{ librenms.memcached_host }}"
      NGINX_ENABLE: "{{ librenms.nginx_enable }}"
      POLLERS: "{{ librenms.pollers }}"
      POLLERS_CRON: "{{ librenms.pollers_cron }}"
      RRDCACHED_CONNECT: "{{ librenms.rrdcached_connect }}"
      RRDCACHED_ENABLE: "false"
  when:
    - librenms.poller
    - librenms.nginx_enable
    - librenms.dns_servers == []
    - librenms.search_domains == []

- name: create librenms poller without nginx
  docker_container:
    name: librenms
    image: "{{ librenms.librenms_container_image }}:{{ librenms.librenms_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    volumes:
      - "{{ librenms.logs_volume }}:/opt/librenms/logs"
      - "{{ librenms.rrd_volume }}:/opt/librenms/rrd"
      - "{{ librenms.conf_d }}:/opt/librenms/conf.d"
      - "{{ librenms.includes }}:/opt/librenms/includes/custom"
    ports:
      - "514:514/udp"
    env:
      ALERTS_ENABLE: "{{ librenms.alerts_enable }}"
      APP_KEY: "{{ librenms.app_key }}"
      BASE_URL: "{{ librenms.base_url }}"
      BILLING_CALCULATE_ENABLE: "{{ librenms.billing_calc_enable }}"
      DAILY_ENABLE: "{{ librenms.daily_enable }}"
      DB_HOST: "{{ librenms.mysql_db_host }}"
      DB_NAME: "{{ librenms.mysql_db_name }}"
      DB_PASS: "{{ librenms.mysql_db_pw }}"
      DB_USER: "{{ librenms.mysql_db_user }}"
      DISCOVERY_ENABLE: "{{ librenms.poller_discovery }}"
      DISCOVERY_THREADS: "{{ librenms.discovery_threads }}"
      ENABLE_SYSLOG: "{{ librenms.enable_syslog }}"
      MEMCACHED_HOST: "{{ librenms.memcached_host }}"
      NGINX_ENABLE: "{{ librenms.nginx_enable }}"
      POLLERS: "{{ librenms.pollers }}"
      POLLERS_CRON: "{{ librenms.pollers_cron }}"
      RRDCACHED_CONNECT: "{{ librenms.rrdcached_connect }}"
      RRDCACHED_ENABLE: "false"
  when:
    - librenms.poller
    - not librenms.nginx_enable
    - librenms.dns_servers == []
    - librenms.search_domains == []

- name: create librenms frontend
  docker_container:
    name: librenms
    image: "{{ librenms.librenms_container_image }}:{{ librenms.librenms_container_tag }}"
    state: "{{ librenms.state }}"
    restart_policy: "{{ librenms.restart_policy }}"
    volumes:
      - "{{ librenms.logs_volume }}:/opt/librenms/logs"
      - "{{ librenms.rrd_volume }}:/opt/librenms/rrd"
      - "{{ librenms.conf_d }}:/opt/librenms/conf.d"
      - "{{ librenms.includes }}:/opt/librenms/includes/custom"
    ports:
      - "80:80"
      - "514:514/udp"
    env:
      ALERTS_ENABLE: "{{ librenms.alerts_enable }}"
      APP_KEY: "{{ librenms.app_key }}"
      BASE_URL: "{{ librenms.base_url }}"
      BILLING_CALCULATE_ENABLE: "{{ librenms.billing_calc_enable }}"
      DAILY_ENABLE: "{{ librenms.daily_enable }}"
      DB_HOST: "{{ librenms.mysql_db_host }}"
      DB_NAME: "{{ librenms.mysql_db_name }}"
      DB_PASS: "{{ librenms.mysql_db_pw }}"
      DB_USER: "{{ librenms.mysql_db_user }}"
      DISCOVERY_ENABLE: "{{ librenms.poller_discovery }}"
      DISCOVERY_THREADS: "{{ librenms.discovery_threads }}"
      ENABLE_SYSLOG: "{{ librenms.enable_syslog }}"
      MEMCACHED_HOST: "{{ librenms.memcached_host }}"
      NGINX_ENABLE: "true"
      POLLERS: "{{ librenms.pollers }}"
      POLLERS_CRON: "{{ librenms.pollers_cron }}"
      POLLERS_ENABLE: "false"
      RRDCACHED_CONNECT: "{{ librenms.rrdcached_connect }}"
      RRDCACHED_ENABLE: "false"
  when: librenms.frontend
